### ISSUE TITLE
Highlighter changed to underline instead of bold

### ISSUE THREAD

**Issue by mfauvain** [G-dH/windows-search-provider#1]
Thx for the extension, very useful. 
Is it possible to keep the highlighting bold by default and not change it to underline?

**Comment by G-dH** [comment]
The reason behind the change in highlighting method is the GS [issue #2479](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2479). This means that without the change, the text of all results will be "randomly" ellipsized, even if there's enough space. You can try disabling the patch by commenting out the following line:
https://github.com/G-dH/windows-search-provider/blob/b8975b9cd2eb2a58317e54ffb4267fbdf04fb6fc/windowsSearchProvider.js#L75
in
`~/.local/share/gnome-shell/extensions/windows-search-provider@G-dH.github.com/windowsSearchProvider.js` file.

**Comment by G-dH** [comment]
I've added an option to change the highlighting style (25b016b). You can install the updated extension from the repository now.

**Comment by mfauvain** [comment]
Very nice. Thank you.
