### ISSUE TITLE
.po file

### ISSUE THREAD

**Issue by yuhldr** [G-dH/windows-search-provider#2]
I want to contribute the translation file `. po`, but I don't know how to use makefile

**Comment by G-dH** [comment]
`make pot` should generate the `.pot` file.

**Comment by yuhldr** [comment]
like #3 , But 'make install' doesn't work

**Comment by G-dH** [comment]
Makefile updated.

**Comment by G-dH** [comment]
I also added your `zh_CN.po` file, let me know how it works for you.

**Comment by yuhldr** [comment]
like this
0|1|2
-|-|-
![截图 2024-03-03 15-46-29](https://github.com/G-dH/windows-search-provider/assets/25719023/8e849358-ab47-4621-bdcc-1df02c67460b)|![截图 2024-03-03 15-46-19](https://github.com/G-dH/windows-search-provider/assets/25719023/e6972017-c34f-403e-bc3b-3ecc98453019)|![截图 2024-03-03 15-47-53](https://github.com/G-dH/windows-search-provider/assets/25719023/1de15913-fa9c-417d-b630-6c25e89f2a16)

**Comment by G-dH** [comment]
At least my part is OK
