### ISSUE TITLE
No need `overview.toggle` for `search-light` ext

### ISSUE THREAD

**Issue by d-enk** [G-dH/windows-search-provider#5]
[search-light](https://github.com/icedman/search-light) 

Сan be checked by `overview.visible` or use `overview.hide`

**Comment by G-dH** [comment]
?

**Comment by d-enk** [comment]
with [search-light](https://github.com/icedman/search-light) you can use search providers without overview

https://github.com/G-dH/windows-search-provider/blob/aa0c00729a3a052c2def0c9d42aea19dfd0b6903/windowsSearchProvider.js#L471-L473

this `overview.toggle()` activate overview

Need use `overview.hide()` or check the overview status yourself by `overview.visible`

**Comment by G-dH** [comment]
It is always good practice to describe the issue before suggesting solutions. ;)

**Comment by G-dH** [comment]
Fixed in `main`/`gnome-42-44` branches. The latest update also adds *move to the current workspace* and *close* buttons to search results, as well as an optional dash icon to toggle WSP search results. Any feedback greatly appreciated.
